// <auto-generated />
using System;
using System.Collections.Generic;
using LotoMln.DataAccess.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LotoMln.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520081630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LotoMln.Models.Entities.CalledNumber", b =>
                {
                    b.Property<string>("RoomCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CalledByPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("RoomCode", "Number");

                    b.ToTable("CalledNumbers");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int[][]>("Grid")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.HasIndex("RoomCode");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.GameStateSnapshot", b =>
                {
                    b.Property<string>("RoomCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid?>("CurrentDrawerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentSlotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PhaseStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<Guid>>("PlayerQueue")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("QueueIndex")
                        .HasColumnType("integer");

                    b.HasKey("RoomCode");

                    b.ToTable("GameStates");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.KinhClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.Property<int>("WinIndex")
                        .HasColumnType("integer");

                    b.Property<string>("WinType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("RoomCode", "ClaimedAt");

                    b.ToTable("KinhClaims");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<int>>("MarkedNumbers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<bool>("UsedRedemption")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("RoomCode");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("integer");

                    b.Property<string[]>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.QuestionSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnsweredByPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("AssignedNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("RoomCode", "AssignedNumber")
                        .IsUnique();

                    b.HasIndex("RoomCode", "Position")
                        .IsUnique();

                    b.ToTable("QuestionSlots");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.Room", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("NameMaxLength")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StealTimeoutSec")
                        .HasColumnType("integer");

                    b.Property<int>("TurnDurationSec")
                        .HasColumnType("integer");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Code");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.StealAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Answer")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("RoomCode", "SlotId");

                    b.ToTable("StealAttempts");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.CalledNumber", b =>
                {
                    b.HasOne("LotoMln.Models.Entities.Room", "Room")
                        .WithMany("CalledNumbers")
                        .HasForeignKey("RoomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.Card", b =>
                {
                    b.HasOne("LotoMln.Models.Entities.Room", "Room")
                        .WithMany("Cards")
                        .HasForeignKey("RoomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.GameStateSnapshot", b =>
                {
                    b.HasOne("LotoMln.Models.Entities.Room", "Room")
                        .WithOne("GameState")
                        .HasForeignKey("LotoMln.Models.Entities.GameStateSnapshot", "RoomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.KinhClaim", b =>
                {
                    b.HasOne("LotoMln.Models.Entities.Room", null)
                        .WithMany("KinhClaims")
                        .HasForeignKey("RoomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LotoMln.Models.Entities.Player", b =>
                {
                    b.HasOne("LotoMln.Models.Entities.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LotoMln.Models.Entities.Room", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.QuestionSlot", b =>
                {
                    b.HasOne("LotoMln.Models.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LotoMln.Models.Entities.Room", "Room")
                        .WithMany("QuestionPool")
                        .HasForeignKey("RoomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("LotoMln.Models.Entities.Room", b =>
                {
                    b.Navigation("CalledNumbers");

                    b.Navigation("Cards");

                    b.Navigation("GameState");

                    b.Navigation("KinhClaims");

                    b.Navigation("Players");

                    b.Navigation("QuestionPool");
                });
#pragma warning restore 612, 618
        }
    }
}
